version: "3"

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env

  app:
    build:
      context: .
    image: anyoneclown/social-media-api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: "redis:alpine"


  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A Social_Media_API worker -l info -P eventlet"
    depends_on:
      - app
      - redis
      - db