# Generated by Django 5.0.1 on 2024-01-17 23:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "social_media",
            "0005_profile_posts_commentary_post_commentaries_like_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="text",
            new_name="content",
        ),
    ]
